### ISSUE TITLE
[Parsing Error]: Import correction and trouble parsing the "data" variable

### ISSUE THREAD

**Issue by BLTSEC** [lnxg33k/MHA#6]
MHA is an awesome tool and I loved the output I received using the Heroku. Thank you very much for creating it! I did however have some issues running MHA locally:

- I believe the from email.Parser import needs to be email.parser
- I also had an issue on line 81, I received "TypeError: initial_value must be str or None, not bytes" 
- I confirmed the headers I used were valid and tested them against the Heroku version without issue
- I confirmed the variable "data" was of type str
- I experimented with using BytesHeaderParser instead of HeaderParser but I didn't find a solution
- Behaviour: The page loads successfully, I paste my headers in, and then click submit. The Traceback is thrown at this point. 

Here's my Traceback:

`Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/MHA-XuZowLoP/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/user/.local/share/virtualenvs/MHA-XuZowLoP/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/user/.local/share/virtualenvs/MHA-XuZowLoP/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/share/virtualenvs/MHA-XuZowLoP/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/user/.local/share/virtualenvs/MHA-XuZowLoP/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/share/virtualenvs/MHA-XuZowLoP/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/share/virtualenvs/MHA-XuZowLoP/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/share/virtualenvs/MHA-XuZowLoP/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/user/.local/share/virtualenvs/MHA-XuZowLoP/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/share/virtualenvs/MHA-XuZowLoP/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/Documents/scripts/Python/MHA/server.py", line 81, in index
    n = HeaderParser().parsestr(data.encode('ascii', 'ignore'))
  File "/usr/lib/python3.6/email/parser.py", line 77, in parsestr
    
  File "/usr/lib/python3.6/email/parser.py", line 68, in parsestr
    """
TypeError: initial_value must be str or None, not bytes`

**Comment by lnxg33k** [comment]
Thanks for the feedback.  MHA was written using Python 2 and not 3
